from __future__ import annotations

from ..models.change import is_missing
from ..models.result import CheckResult
from ..scoring.risk import severity_rank
from ._explain import recommended_action, why_it_matters


def render_markdown(result: CheckResult) -> str:
    out = []
    out.append("# Regression Firewall Report")
    out.append("")
    project = result.project or {}
    out.append(f"- **Project:** {project.get('name', '?')} ({project.get('language', '?')})")
    out.append(f"- **Generated:** {result.created_at}")
    out.append(f"- **Tool:** regression-firewall {result.tool_version}")
    out.append(f"- **Verdict:** **{result.verdict}**")
    out.append(f"- **Risk score:** {result.score} / 100"
               + (" (floored to match verdict rules)" if result.score_floored else ""))
    if result.intent_task:
        out.append(f"- **Intent:** {result.intent_task}")
    if result.intent_source == "none":
        out.append("- **Intent:** none provided — all changes below are treated as unrequested")
    out.append("")

    summary = result.summary
    out.append(
        f"**Summary:** {summary.get('expected', 0)} expected, "
        f"{summary.get('unexpected', 0)} unexpected, {summary.get('uncertain', 0)} uncertain."
    )
    out.append("")

    for warning in result.warnings:
        out.append(f"> ⚠️ {warning}")
        out.append("")
    if result.config_changed_since_baseline:
        out.append("> ⚠️ The configuration changed since the baseline was captured; "
                   "re-baseline if this was intended.")
        out.append("")
    if result.baseline_trust_warning:
        out.append("> **BASELINE TRUST WARNING**: the baseline appears to have been "
                   "captured after the working tree changed (its previous check "
                   "reported a regression). It may no longer represent pre-change "
                   "behavior; treat this result with reduced trust.")
        out.append("")

    unexpected = sorted(
        (c for c in result.changes if c.classification != "expected"),
        key=lambda c: (-severity_rank(c.severity), c.target, c.category),
    )
    expected = [c for c in result.changes if c.classification == "expected"]

    if unexpected:
        out.append("## Unexpected Changes")
        out.append("")
        for change in unexpected:
            title = change.path or change.target
            out.append(f"### {change.severity.upper()} — {change.target} — {change.category}")
            if change.path and change.path != change.target:
                out.append(f"**Location:** `{change.path}`")
            out.append("")
            out.append(f"| | |")
            out.append(f"|---|---|")
            out.append(f"| Before | `{_fmt(change.before)}` |")
            out.append(f"| After | `{_fmt(change.after)}` |")
            out.append(f"| Requested | no evidence in intent |")
            out.append(f"| Confidence | {int(round(change.confidence * 100))}% |")
            out.append("")
            out.append(f"**Why this matters:** {why_it_matters(change.category)}")
            out.append("")
            out.append(f"**What to verify:** {recommended_action(change.category)}")
            out.append("")

    if expected:
        out.append("## Expected Changes (matched intent)")
        out.append("")
        out.append("| Target | Category | Transition | Note |")
        out.append("|---|---|---|---|")
        for change in expected:
            out.append(
                f"| {change.target} | {change.category} "
                f"| {_fmt(change.before)} → {_fmt(change.after)} | {change.note or ''} |"
            )
        out.append("")

    if not unexpected and not expected:
        out.append("No behavior changes were detected.")
        out.append("")

    out.append("---")
    out.append(
        "*Generated by Regression Firewall. `BLOCK` means the task should not be "
        "declared complete until the reported changes are fixed or confirmed intentional.*"
    )
    return "\n".join(out)


def _fmt(value) -> str:
    if is_missing(value) or value is None:
        return "&lt;absent&gt;"
    if isinstance(value, str):
        text = value.replace("\n", "\\n").replace("|", "\\|")
        return text if len(text) <= 60 else text[:57] + "..."
    if isinstance(value, (dict, list)):
        import json

        text = json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
        return text if len(text) <= 60 else text[:57] + "..."
    return str(value)
